import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

/*
  The credential documents a doctor sends with their application.

  These used to be stored as a file name and nothing else, so an
  administrator was asked to verify a medical licence while looking at
  the word "licence.pdf". The files themselves are written to disk here,
  outside the web root, and are only ever read back through an admin
  route that checks who is asking.
*/
export const DOCUMENT_KINDS = [
  "id-document",
  "medical-license",
  "specialty-certificate",
  "cv",
] as const;

export type DocumentKind = (typeof DOCUMENT_KINDS)[number];

export const DOCUMENT_LABELS: Record<DocumentKind, string> = {
  "id-document": "ID document",
  "medical-license": "Medical license",
  "specialty-certificate": "Specialty certificate",
  cv: "CV",
};

/* A licence scan is a photo or a PDF, never a program. */
const ALLOWED_EXTENSIONS = [
  ".pdf",
  ".jpg",
  ".jpeg",
  ".png",
  ".webp",
];

const MAXIMUM_FILE_SIZE = 10 * 1024 * 1024;

export function documentsDirectory(applicationId: string) {
  return path.join(
    process.cwd(),
    "storage",
    "doctor-documents",
    /*
      The identifier is generated by the server and contains no path
      separators, but it is stripped anyway: a directory name built from
      request data must never be able to climb out of its parent.
    */
    path.basename(applicationId),
  );
}

export function contentTypeFor(filePath: string) {
  const extension = path.extname(filePath).toLowerCase();

  if (extension === ".pdf") return "application/pdf";
  if (extension === ".png") return "image/png";
  if (extension === ".webp") return "image/webp";
  if (extension === ".jpg" || extension === ".jpeg") return "image/jpeg";

  return "application/octet-stream";
}

/*
  Writes one uploaded document and returns the path to store in the
  application row. Returns a message instead when the file is not
  something a credential document can be.
*/
export async function saveDoctorDocument(options: {
  applicationId: string;
  kind: DocumentKind;
  file: File;
}): Promise<{ storedPath: string } | { error: string }> {
  const { applicationId, kind, file } = options;

  const label = DOCUMENT_LABELS[kind];

  if (file.size === 0) {
    return { error: `The ${label} file is empty.` };
  }

  if (file.size > MAXIMUM_FILE_SIZE) {
    return { error: `The ${label} must be 10 MB or smaller.` };
  }

  const extension = path.extname(file.name).toLowerCase();

  if (!ALLOWED_EXTENSIONS.includes(extension)) {
    return {
      error: `The ${label} must be a PDF or an image (${ALLOWED_EXTENSIONS.join(
        ", ",
      )}).`,
    };
  }

  const directory = documentsDirectory(applicationId);

  await mkdir(directory, { recursive: true });

  /*
    The stored name comes from the kind, not from what the sender called
    the file, so an uploaded name can neither collide with another nor
    reach a directory of its own choosing.
  */
  const storedName = `${kind}${extension}`;

  await writeFile(
    path.join(directory, storedName),
    Buffer.from(await file.arrayBuffer()),
  );

  return {
    storedPath: path
      .join("storage", "doctor-documents", path.basename(applicationId), storedName)
      .replace(/\\/g, "/"),
  };
}
