import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

/*
  The papers a secretary sends with their application.

  A secretary is not a clinician, so this is a shorter list than the
  doctor's: no medical licence, no specialty certificate, because
  neither exists for this job. What is asked for is identity, the
  qualification that trained them for the desk, and whatever proof of
  previous work they have.

  Only the first two are required. An applicant fresh out of college has
  no experience letter and no CV worth the name, and refusing them the
  form over paper they cannot possibly hold would filter for age rather
  than for suitability.
*/
export const SECRETARY_DOCUMENT_KINDS = [
  "id-document",
  "qualification-certificate",
  "experience-certificate",
  "cv",
] as const;

export type SecretaryDocumentKind =
  (typeof SECRETARY_DOCUMENT_KINDS)[number];

export const SECRETARY_DOCUMENT_LABELS: Record<
  SecretaryDocumentKind,
  string
> = {
  "id-document": "ID document",
  "qualification-certificate": "Qualification certificate",
  "experience-certificate": "Experience certificate",
  cv: "CV",
};

/* The two an application cannot be sent without. */
export const REQUIRED_SECRETARY_DOCUMENTS: SecretaryDocumentKind[] = [
  "id-document",
  "qualification-certificate",
];

/* A certificate is a scan or a PDF, never a program. */
const ALLOWED_EXTENSIONS = [".pdf", ".jpg", ".jpeg", ".png", ".webp"];

const MAXIMUM_FILE_SIZE = 10 * 1024 * 1024;

export function secretaryDocumentsDirectory(applicationId: string) {
  return path.join(
    process.cwd(),
    "storage",
    "secretary-documents",
    /*
      The identifier is generated by the server and holds no path
      separators, but it is stripped anyway: a directory name built from
      request data must never be able to climb out of its parent.
    */
    path.basename(applicationId),
  );
}

export function secretaryContentTypeFor(filePath: string) {
  const extension = path.extname(filePath).toLowerCase();

  if (extension === ".pdf") return "application/pdf";
  if (extension === ".png") return "image/png";
  if (extension === ".webp") return "image/webp";
  if (extension === ".jpg" || extension === ".jpeg") return "image/jpeg";

  return "application/octet-stream";
}

/*
  Writes one uploaded document and returns the path to store on the
  application row. Returns a message instead when the file is not
  something a certificate can be.
*/
export async function saveSecretaryDocument(options: {
  applicationId: string;
  kind: SecretaryDocumentKind;
  file: File;
}): Promise<{ storedPath: string } | { error: string }> {
  const { applicationId, kind, file } = options;

  const label = SECRETARY_DOCUMENT_LABELS[kind];

  if (file.size === 0) {
    return { error: `The ${label} file is empty.` };
  }

  if (file.size > MAXIMUM_FILE_SIZE) {
    return { error: `The ${label} must be 10 MB or smaller.` };
  }

  const extension = path.extname(file.name).toLowerCase();

  if (!ALLOWED_EXTENSIONS.includes(extension)) {
    return {
      error: `The ${label} must be a PDF or an image (${ALLOWED_EXTENSIONS.join(
        ", ",
      )}).`,
    };
  }

  const directory = secretaryDocumentsDirectory(applicationId);

  await mkdir(directory, { recursive: true });

  /*
    The stored name comes from the kind, not from what the sender called
    the file, so an uploaded name can neither collide with another nor
    reach a directory of its own choosing.
  */
  const storedName = `${kind}${extension}`;

  await writeFile(
    path.join(directory, storedName),
    Buffer.from(await file.arrayBuffer()),
  );

  return {
    storedPath: path
      .join(
        "storage",
        "secretary-documents",
        path.basename(applicationId),
        storedName,
      )
      .replace(/\\/g, "/"),
  };
}
